### ISSUE TITLE
[Bug] - <bug issue>und und die
Wolte

### ISSUE THREAD

**Issue by adwokat** [OasisDEX/oasis-borrow#930]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop/Smartphone (please complete the following information):**
 - Connection method [e.g. Metamask, Ledger, Trezor]

**Additional context**

**Comment by FBrinkkemper** [comment]
@adwokat I'm closing this as the description isn't filled. If you have any issues, please report a new issue.
